In [2]:
import numpy as np
import pandas as pd
from random import uniform

#Generando Datos
nro_solsis=2000
Celestial_body = np.zeros((nro_solsis*9,3))
y = np.zeros((nro_solsis*9,9))

for i in range(0,nro_solsis):
	#Volumen	/(10^10)
	#Masa		/(10^10)
    #Densidad
    #Temperatura Superficie
    #Nro de elem
    #Orbita??
    #Es Orbitado?
    
	#Datos Sol
	Celestial_body[i,0] = uniform(1.3923*(10**8),1.4323*(10**8)) #1.4123*(10^18)
	Celestial_body[i,1] = uniform(1.9691*(10**20),2.0091*(10**20)) #1.9891*(10^30)
	Celestial_body[i,2] = Celestial_body[i,1]/Celestial_body[i,0]

	y[i,0] = 1
	#Datos Mercurio
	Celestial_body[i+nro_solsis,0] = uniform(6.063,6.103) #6.083*(10^10)
	Celestial_body[i+nro_solsis,1] = uniform(3.282*(10**13),3.322*(10**13)) #3.302*(10^23)
	Celestial_body[i+nro_solsis,2] = Celestial_body[i+nro_solsis,1]/Celestial_body[i+nro_solsis,0]

	y[i+nro_solsis,1] = 1
	#Datos Venus
	Celestial_body[i+nro_solsis*2,0] = uniform(9.26*(10),9.30*(10)) #9.28*(10^11)
	Celestial_body[i+nro_solsis*2,1] = uniform(4.849*(10**14),4.889*(10**14)) #4.869*(10^24)
	Celestial_body[i+nro_solsis*2,2] = Celestial_body[i+nro_solsis*2,1]/Celestial_body[i+nro_solsis*2,0]

	y[i+nro_solsis*2,2] = 1
	#Datos Tierra
	Celestial_body[i+nro_solsis*3,0] = uniform(1.06321*(10**2),1.10321*(10**2)) #1.08321*(10^12)
	Celestial_body[i+nro_solsis*3,1] = uniform(5.9536*(10**14),5.9936*(10**14)) #5.9736*(10^24)
	Celestial_body[i+nro_solsis*3,2] = Celestial_body[i+nro_solsis*3,1]/Celestial_body[i+nro_solsis*3,0]

	y[i+nro_solsis*3,3] = 1
	#Datos Marte
	Celestial_body[i+nro_solsis*4,0] = uniform(1.6118*(10),1.6518*(10)) #1.6318*(10^11)
	Celestial_body[i+nro_solsis*4,1] = uniform(6.3985*(10**13),6.4385*(10**13)) #6.4185*(10^23)
	Celestial_body[i+nro_solsis*4,2] = Celestial_body[i+nro_solsis*4,1]/Celestial_body[i+nro_solsis*4,0]

	y[i+nro_solsis*4,4] = 1
	#Datos Jupiter
	Celestial_body[i+nro_solsis*5,0] = uniform(1.4113*(10**15),1.4513*(10**15)) #1.4313*(10^15)
	Celestial_body[i+nro_solsis*5,1] = uniform(1.879*(10**17),1.919*(10**17)) #1.899*(10^27)
	Celestial_body[i+nro_solsis*5,2] = Celestial_body[i+nro_solsis*5,1]/Celestial_body[i+nro_solsis*5,0]

	y[i+nro_solsis*5,5] = 1
	#Datos Saturno
	Celestial_body[i+nro_solsis*6,0] = uniform(8.25*(10**13),8.29*(10**13)) #8.27*(10^23)
	Celestial_body[i+nro_solsis*6,1] = uniform(5.688*(10**16),5.688*(10**16)) #5.688*(10^26)
	Celestial_body[i+nro_solsis*6,2] = Celestial_body[i+nro_solsis*6,1]/Celestial_body[i+nro_solsis*6,0]

	y[i+nro_solsis*6,6] = 1
	#Datos Urano
	Celestial_body[i+nro_solsis*7,0] = uniform(6.833*(10**3),6.833*(10**3)) #6.833*(10^13)
	Celestial_body[i+nro_solsis*7,1] = uniform(8.666*(10**15),8.706*(10**15)) #8.686*(10^25)
	Celestial_body[i+nro_solsis*7,2] = Celestial_body[i+nro_solsis*7,1]/Celestial_body[i+nro_solsis*7,0]

	y[i+nro_solsis*7,7] = 1
	#Datos Neptuno
	Celestial_body[i+nro_solsis*8,0] = uniform(6.234*(10**3),6.274*(10**3)) #6.254*(10^13)
	Celestial_body[i+nro_solsis*8,1] = uniform(1.004*(10**16),1.044*(10**16)) #1.024*(10^26)
	Celestial_body[i+nro_solsis*8,2] = Celestial_body[i+nro_solsis*8,1]/Celestial_body[i+nro_solsis*8,0]

	y[i+nro_solsis*8,8] = 1
    
print("--Dataset sin Normalizar--")
print(Celestial_body)
print(y)

#Normalizar DataSet
Celestial_body = (Celestial_body - np.mean(Celestial_body,axis=0))/(np.std(Celestial_body,axis=0))

#Imprimir :V
print("--Dataset Normalizado--")
print(Celestial_body)
print(y)

--Dataset sin Normalizar--
[[1.41896270e+08 1.99412448e+20 1.40533961e+12]
 [1.41128099e+08 2.00341621e+20 1.41957287e+12]
 [1.40005765e+08 1.97818914e+20 1.41293406e+12]
 ...
 [6.24933424e+03 1.01856428e+16 1.62987646e+12]
 [6.25834812e+03 1.03164402e+16 1.64842863e+12]
 [6.25071054e+03 1.02171920e+16 1.63456490e+12]]
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
--Dataset Normalizado--
[[-0.37605875  2.83629005 -0.60086577]
 [-0.37605875  2.85115574 -0.5943379 ]
 [-0.37605875  2.81079533 -0.59738269]
 ...
 [-0.37605907 -0.35391733 -0.49788529]
 [-0.37605907 -0.35391524 -0.48937662]
 [-0.37605907 -0.35391683 -0.49573501]]
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


C:\Users\pay-7\AppData\Local\Temp\ipykernel_12228\53075561.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [3]:
#Generando Val y Test DataSet
nro_solsis_ct=650
Celestial_body_val = np.zeros((nro_solsis_ct*9,3))
y_val = np.zeros((nro_solsis_ct*9,9))
Celestial_body_test = np.zeros((nro_solsis_ct*9,3))
y_test = np.zeros((nro_solsis_ct*9,9))

for i in range(0,nro_solsis_ct):
	#Volumen	/(10^10)
	#Masa		/(10^10)
    
	#Datos Sol
    Celestial_body_val[i,0] = uniform(1.3923*(10**8),1.4323*(10**8))
    Celestial_body_val[i,1] = uniform(1.9691*(10**20),2.0091*(10**20))
    Celestial_body_val[i,2] = Celestial_body_val[i,1]/Celestial_body_val[i,0]

    y_val[i,0] = 1
    
    Celestial_body_test[i,0] = uniform(1.3923*(10**8),1.4323*(10**8)) 
    Celestial_body_test[i,1] = uniform(1.9691*(10**20),2.0091*(10**20))
    Celestial_body_test[i,2] = Celestial_body_test[i,1]/Celestial_body_test[i,0]

    y_test[i,0] = 1
    
	#Datos Mercurio
    Celestial_body_val[i+nro_solsis_ct,0] = uniform(6.063,6.103) #6.083*(10^10)
    Celestial_body_val[i+nro_solsis_ct,1] = uniform(3.282*(10**13),3.322*(10**13)) #3.302*(10^23)
    Celestial_body_val[i+nro_solsis_ct,2] = Celestial_body_val[i+nro_solsis_ct,1]/Celestial_body_val[i+nro_solsis_ct,0]

    y_val[i+nro_solsis_ct,1] = 1
    
    Celestial_body_test[i+nro_solsis_ct,0] = uniform(6.063,6.103) #6.083*(10^10)
    Celestial_body_test[i+nro_solsis_ct,1] = uniform(3.282*(10**13),3.322*(10**13)) #3.302*(10^23)
    Celestial_body_test[i+nro_solsis_ct,2] = Celestial_body_test[i+nro_solsis_ct,1]/Celestial_body_test[i+nro_solsis_ct,0]

    y_test[i+nro_solsis_ct,1] = 1
    
	#Datos Venus
    Celestial_body_val[i+nro_solsis_ct*2,0] = uniform(9.26*(10),9.30*(10)) #9.28*(10^11)
    Celestial_body_val[i+nro_solsis_ct*2,1] = uniform(4.849*(10**14),4.889*(10**14)) #4.869*(10^24)
    Celestial_body_val[i+nro_solsis_ct*2,2] = Celestial_body_val[i+nro_solsis_ct*2,1]/Celestial_body_val[i+nro_solsis_ct*2,0]

    y_val[i+nro_solsis_ct*2,2] = 1
    
    Celestial_body_test[i+nro_solsis_ct*2,0] = uniform(9.26*(10),9.30*(10)) #9.28*(10^11)
    Celestial_body_test[i+nro_solsis_ct*2,1] = uniform(4.849*(10**14),4.889*(10**14)) #4.869*(10^24)
    Celestial_body_test[i+nro_solsis_ct*2,2] = Celestial_body_test[i+nro_solsis_ct*2,1]/Celestial_body_test[i+nro_solsis_ct*2,0]

    y_test[i+nro_solsis_ct*2,2] = 1
    
	#Datos Tierra
    Celestial_body_val[i+nro_solsis_ct*3,0] = uniform(1.06321*(10**2),1.10321*(10**2)) #1.08321*(10^12)
    Celestial_body_val[i+nro_solsis_ct*3,1] = uniform(5.9536*(10**14),5.9936*(10**14)) #5.9736*(10^24)
    Celestial_body_val[i+nro_solsis_ct*3,2] = Celestial_body_val[i+nro_solsis_ct*3,1]/Celestial_body_val[i+nro_solsis_ct*3,0]

    y_val[i+nro_solsis_ct*3,3] = 1
    
    Celestial_body_test[i+nro_solsis_ct*3,0] = uniform(1.06321*(10**2),1.10321*(10**2)) #1.08321*(10^12)
    Celestial_body_test[i+nro_solsis_ct*3,1] = uniform(5.9536*(10**14),5.9936*(10**14)) #5.9736*(10^24)
    Celestial_body_test[i+nro_solsis_ct*3,2] = Celestial_body_test[i+nro_solsis_ct*3,1]/Celestial_body_test[i+nro_solsis_ct*3,0]

    y_test[i+nro_solsis_ct*3,3] = 1
    
	#Datos Marte
    Celestial_body_val[i+nro_solsis_ct*4,0] = uniform(1.6118*(10),1.6518*(10)) #1.6318*(10^11)
    Celestial_body_val[i+nro_solsis_ct*4,1] = uniform(6.3985*(10**13),6.4385*(10**13)) #6.4185*(10^23)
    Celestial_body_val[i+nro_solsis_ct*4,2] = Celestial_body_val[i+nro_solsis_ct*4,1]/Celestial_body_val[i+nro_solsis_ct*4,0]

    y_val[i+nro_solsis_ct*4,4] = 1

    Celestial_body_test[i+nro_solsis_ct*4,0] = uniform(1.6118*(10),1.6518*(10)) #1.6318*(10^11)
    Celestial_body_test[i+nro_solsis_ct*4,1] = uniform(6.3985*(10**13),6.4385*(10**13)) #6.4185*(10^23)
    Celestial_body_test[i+nro_solsis_ct*4,2] = Celestial_body_test[i+nro_solsis_ct*4,1]/Celestial_body_test[i+nro_solsis_ct*4,0]

    y_test[i+nro_solsis_ct*4,4] = 1
    
	#Datos Jupiter
    Celestial_body_val[i+nro_solsis_ct*5,0] = uniform(1.4113*(10**15),1.4513*(10**15)) #1.4313*(10^15)
    Celestial_body_val[i+nro_solsis_ct*5,1] = uniform(1.879*(10**17),1.919*(10**17)) #1.899*(10^27)
    Celestial_body_val[i+nro_solsis_ct*5,2] = Celestial_body_val[i+nro_solsis_ct*5,1]/Celestial_body_val[i+nro_solsis_ct*5,0]

    y_val[i+nro_solsis_ct*5,5] = 1
    
    Celestial_body_test[i+nro_solsis_ct*5,0] = uniform(1.4113*(10**15),1.4513*(10**15)) #1.4313*(10^15)
    Celestial_body_test[i+nro_solsis_ct*5,1] = uniform(1.879*(10**17),1.919*(10**17)) #1.899*(10^27)
    Celestial_body_test[i+nro_solsis_ct*5,2] = Celestial_body_test[i+nro_solsis_ct*5,1]/Celestial_body_test[i+nro_solsis_ct*5,0]

    y_test[i+nro_solsis_ct*5,5] = 1
	#Datos Saturno
    Celestial_body_val[i+nro_solsis_ct*6,0] = uniform(8.25*(10**13),8.29*(10**13)) #8.27*(10^23)
    Celestial_body_val[i+nro_solsis_ct*6,1] = uniform(5.688*(10**16),5.688*(10**16)) #5.688*(10^26)
    Celestial_body_val[i+nro_solsis_ct*6,2] = Celestial_body_val[i+nro_solsis_ct*6,1]/Celestial_body_val[i+nro_solsis_ct*6,0]

    y_val[i+nro_solsis_ct*6,6] = 1
    
    Celestial_body_test[i+nro_solsis_ct*6,0] = uniform(8.25*(10**13),8.29*(10**13)) #8.27*(10^23)
    Celestial_body_test[i+nro_solsis_ct*6,1] = uniform(5.688*(10**16),5.688*(10**16)) #5.688*(10^26)
    Celestial_body_test[i+nro_solsis_ct*6,2] = Celestial_body_test[i+nro_solsis_ct*6,1]/Celestial_body_test[i+nro_solsis_ct*6,0]

    y_test[i+nro_solsis_ct*6,6] = 1
    
	#Datos Urano
    Celestial_body_val[i+nro_solsis_ct*7,0] = uniform(6.833*(10**3),6.833*(10**3)) #6.833*(10^13)
    Celestial_body_val[i+nro_solsis_ct*7,1] = uniform(8.666*(10**15),8.706*(10**15)) #8.686*(10^25)
    Celestial_body_val[i+nro_solsis_ct*7,2] = Celestial_body_val[i+nro_solsis_ct*7,1]/Celestial_body_val[i+nro_solsis_ct*7,0]

    y_val[i+nro_solsis_ct*7,7] = 1
    
    Celestial_body_test[i+nro_solsis_ct*7,0] = uniform(6.833*(10**3),6.833*(10**3)) #6.833*(10^13)
    Celestial_body_test[i+nro_solsis_ct*7,1] = uniform(8.666*(10**15),8.706*(10**15)) #8.686*(10^25)
    Celestial_body_test[i+nro_solsis_ct*7,2] = Celestial_body_test[i+nro_solsis_ct*7,1]/Celestial_body_test[i+nro_solsis_ct*7,0]

    y_test[i+nro_solsis_ct*7,7] = 1
    
	#Datos Neptuno
    Celestial_body_val[i+nro_solsis_ct*8,0] = uniform(6.234*(10**3),6.274*(10**3)) #6.254*(10^13)
    Celestial_body_val[i+nro_solsis_ct*8,1] = uniform(1.004*(10**16),1.044*(10**16)) #1.024*(10^26)
    Celestial_body_val[i+nro_solsis_ct*8,2] = Celestial_body_val[i+nro_solsis_ct*8,1]/Celestial_body_val[i+nro_solsis_ct*8,0]

    y_val[i+nro_solsis_ct*8,8] = 1
    
    Celestial_body_test[i+nro_solsis_ct*8,0] = uniform(6.234*(10**3),6.274*(10**3)) #6.254*(10^13)
    Celestial_body_test[i+nro_solsis_ct*8,1] = uniform(1.004*(10**16),1.044*(10**16)) #1.024*(10^26)
    Celestial_body_test[i+nro_solsis_ct*8,2] = Celestial_body_test[i+nro_solsis_ct*8,1]/Celestial_body_test[i+nro_solsis_ct*8,0]

    y_test[i+nro_solsis_ct*8,8] = 1

print("--Validation Dataset sin Normalizar--")
print(Celestial_body_val)
print(y_val)
print("--Test Dataset sin Normalizar--")
print(Celestial_body_test)
print(y_test)

#Normalizar DataSet
Celestial_body_val = (Celestial_body_val - np.mean(Celestial_body_val,axis=0))/(np.std(Celestial_body_val,axis=0))
Celestial_body_test = (Celestial_body_test - np.mean(Celestial_body_test,axis=0))/(np.std(Celestial_body_test,axis=0))

#Imprimir :V
print("--Validation Dataset Normalizado--")
print(Celestial_body_val)
print(y_val)
print("--Test Dataset Normalizado--")
print(Celestial_body_test)
print(y_test)

--Validation Dataset sin Normalizar--
[[1.42202478e+08 2.00276056e+20 1.40838654e+12]
 [1.40452028e+08 1.98927203e+20 1.41633557e+12]
 [1.39870484e+08 1.98674194e+20 1.42041544e+12]
 ...
 [6.24164329e+03 1.01853809e+16 1.63184284e+12]
 [6.26644303e+03 1.03235325e+16 1.64743100e+12]
 [6.24544237e+03 1.03876370e+16 1.66323478e+12]]
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
--Test Dataset sin Normalizar--
[[1.39719087e+08 1.98267853e+20 1.41904630e+12]
 [1.39510141e+08 1.99807016e+20 1.43220424e+12]
 [1.43088559e+08 1.98449262e+20 1.38689818e+12]
 ...
 [6.25260758e+03 1.01379783e+16 1.62140005e+12]
 [6.26385480e+03 1.03231217e+16 1.64804614e+12]
 [6.26850302e+03 1.01002890e+16 1.61127608e+12]]
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
--Validation Dataset Normaliza

In [4]:
#Comvertir a csv

Celestial_body = np.array(Celestial_body)
Celestial_body = Celestial_body.flatten()
Celestial_body = np.array(Celestial_body)
Celestial_body = pd.DataFrame(Celestial_body)
Celestial_body.to_csv('DataSet_Celestial_Body.csv', sep=',', encoding='utf-8')

Celestial_body_val = np.array(Celestial_body_val)
Celestial_body_val = Celestial_body_val.flatten()
Celestial_body_val = np.array(Celestial_body_val)
Celestial_body_val = pd.DataFrame(Celestial_body_val)
Celestial_body_val.to_csv('DataSet_Celestial_Body_val.csv', sep=',', encoding='utf-8')

Celestial_body_test = np.array(Celestial_body_test)
Celestial_body_test = Celestial_body_test.flatten()
Celestial_body_test = np.array(Celestial_body_test)
Celestial_body_test = pd.DataFrame(Celestial_body_test)
Celestial_body_test.to_csv('DataSet_Celestial_Body_test.csv', sep=',', encoding='utf-8')

y = np.array(y)
y = y.flatten()
y = np.array(y)
y = pd.DataFrame(y)
y.to_csv('Outputs_Celestial_Body.csv', sep=',', encoding='utf-8')

y_val = np.array(y_val)
y_val = y_val.flatten()
y_val = np.array(y_val)
y_val = pd.DataFrame(y_val)
y_val.to_csv('Outputs_Celestial_Body_val.csv', sep=',', encoding='utf-8')

y_test = np.array(y_test)
y_test = y_test.flatten()
y_test = np.array(y_test)
y_test = pd.DataFrame(y_test)
y_test.to_csv('Outputs_Celestial_Body_test.csv', sep=',', encoding='utf-8')

#Imprimir :V
print("--Dataset csv--")
print(Celestial_body)
print(y)
print("--Validation Dataset csv--")
print(Celestial_body_val)
print(y_val)
print("--Test Dataset csv--")
print(Celestial_body_test)
print(y_test)

--Dataset csv--
              0
0     -0.376059
1      2.836290
2     -0.600866
3     -0.376059
4      2.851156
...         ...
53995 -0.353915
53996 -0.489377
53997 -0.376059
53998 -0.353917
53999 -0.495735

[54000 rows x 1 columns]
          0
0       1.0
1       0.0
2       0.0
3       0.0
4       0.0
...     ...
161995  0.0
161996  0.0
161997  0.0
161998  0.0
161999  1.0

[162000 rows x 1 columns]
--Validation Dataset csv--
              0
0     -0.376072
1      2.849634
2     -0.599507
3     -0.376072
4      2.828057
...         ...
17545 -0.353915
17546 -0.489899
17547 -0.376072
17548 -0.353914
17549 -0.482653

[17550 rows x 1 columns]
         0
0      1.0
1      0.0
2      0.0
3      0.0
4      0.0
...    ...
52645  0.0
52646  0.0
52647  0.0
52648  0.0
52649  1.0

[52650 rows x 1 columns]
--Test Dataset csv--
              0
0     -0.376067
1      2.818342
2     -0.594640
3     -0.376067
4      2.842970
...         ...
17545 -0.353915
17546 -0.489638
17547 -0.376068
17548 -0.35